'''
Copyright 2025 Advanced Micro Devices, Inc.
All rights reserved. This notice is intended as a precaution against inadvertent
publication and does not imply publication or any waiver of confidentiality.
The year included in the foregoing notice is the year of creation of the work.
All code contained here is Property of Advanced Micro Devices, Inc.

AUTO-GENERATED by build_tools/gen_anc_suites.py
Do NOT edit by hand. ANC Oblex item suite: one ``test_<item>``
function per ANC item.

Edit the group/item lists in cvs/lib/anc_lib.py and re-run
``make gen-anc-suites`` to regenerate. Each function ensures ANC is installed
and ROCm ldconfig is fixed (session-cached via anc_lib.ensure_anc_ready), then
runs its one item; logs go to
{runner_log_folder}/anc_logs/<node>/test_<item>/<timestamp>.

Run every item:    cvs run anc_test_oblex ...
Run a single item: cvs run anc_test_oblex test_<item> ...
List the items:    cvs list anc_test_oblex
'''

from cvs.lib import anc_lib


def test_oblex_ds(orch, cluster_dict, config_dict, request):
    '''Run the ANC item "oblex_ds".'''
    anc_lib.ensure_anc_ready(orch, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        orch,
        cluster_dict,
        config_dict,
        ["oblex_ds"],
        "test_oblex_ds",
        request=request,
    )


def test_oblex_ds_ntd(orch, cluster_dict, config_dict, request):
    '''Run the ANC item "oblex_ds_ntd".'''
    anc_lib.ensure_anc_ready(orch, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        orch,
        cluster_dict,
        config_dict,
        ["oblex_ds_ntd"],
        "test_oblex_ds_ntd",
        request=request,
    )


def test_oblex_metronome(orch, cluster_dict, config_dict, request):
    '''Run the ANC item "oblex_metronome".'''
    anc_lib.ensure_anc_ready(orch, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        orch,
        cluster_dict,
        config_dict,
        ["oblex_metronome"],
        "test_oblex_metronome",
        request=request,
    )


def test_oblex_opt(orch, cluster_dict, config_dict, request):
    '''Run the ANC item "oblex_opt".'''
    anc_lib.ensure_anc_ready(orch, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        orch,
        cluster_dict,
        config_dict,
        ["oblex_opt"],
        "test_oblex_opt",
        request=request,
    )


def test_oblex_remix2(orch, cluster_dict, config_dict, request):
    '''Run the ANC item "oblex_remix2".'''
    anc_lib.ensure_anc_ready(orch, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        orch,
        cluster_dict,
        config_dict,
        ["oblex_remix2"],
        "test_oblex_remix2",
        request=request,
    )


def test_oblex_s16(orch, cluster_dict, config_dict, request):
    '''Run the ANC item "oblex_s16".'''
    anc_lib.ensure_anc_ready(orch, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        orch,
        cluster_dict,
        config_dict,
        ["oblex_s16"],
        "test_oblex_s16",
        request=request,
    )


def test_oblex_s16_ds(orch, cluster_dict, config_dict, request):
    '''Run the ANC item "oblex_s16_ds".'''
    anc_lib.ensure_anc_ready(orch, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        orch,
        cluster_dict,
        config_dict,
        ["oblex_s16_ds"],
        "test_oblex_s16_ds",
        request=request,
    )


def test_oblex_trad(orch, cluster_dict, config_dict, request):
    '''Run the ANC item "oblex_trad".'''
    anc_lib.ensure_anc_ready(orch, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        orch,
        cluster_dict,
        config_dict,
        ["oblex_trad"],
        "test_oblex_trad",
        request=request,
    )
