'''
Copyright 2025 Advanced Micro Devices, Inc.
All rights reserved. This notice is intended as a precaution against inadvertent
publication and does not imply publication or any waiver of confidentiality.
The year included in the foregoing notice is the year of creation of the work.
All code contained here is Property of Advanced Micro Devices, Inc.

AUTO-GENERATED by build_tools/gen_anc_suites.py
Do NOT edit by hand. ANC GPU group suite: one ``test_<group>``
function per ANC gpu group.

Edit CPU_GROUPS / GPU_GROUPS in cvs/lib/anc_lib.py and re-run
``make gen-anc-suites`` to regenerate. Each function ensures ANC is installed
and ROCm ldconfig is fixed (session-cached via anc_lib.ensure_anc_ready), then
runs its one group; logs go to
{runner_log_folder}/anc_logs/<node>/test_<group>/<timestamp>.

Run every gpu group:  cvs run anc_test_gpu ...
Run a single group:      cvs run anc_test_gpu test_<group> ...
List the groups:         cvs list anc_test_gpu
'''

from cvs.lib import anc_lib


def test_gpu_content_check(phdl, cluster_dict, config_dict, request):
    '''Run the ANC group "gpu_content_check".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_groups(
        phdl,
        cluster_dict,
        config_dict,
        ["gpu_content_check"],
        "test_gpu_content_check",
        request=request,
    )


def test_gpu_mfg_l10(phdl, cluster_dict, config_dict, request):
    '''Run the ANC group "gpu_mfg_l10".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_groups(
        phdl,
        cluster_dict,
        config_dict,
        ["gpu_mfg_l10"],
        "test_gpu_mfg_l10",
        request=request,
    )


def test_hbm_lvl1(phdl, cluster_dict, config_dict, request):
    '''Run the ANC group "hbm_lvl1".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_groups(
        phdl,
        cluster_dict,
        config_dict,
        ["hbm_lvl1"],
        "test_hbm_lvl1",
        request=request,
    )


def test_hbm_lvl2(phdl, cluster_dict, config_dict, request):
    '''Run the ANC group "hbm_lvl2".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_groups(
        phdl,
        cluster_dict,
        config_dict,
        ["hbm_lvl2"],
        "test_hbm_lvl2",
        request=request,
    )


def test_hbm_lvl3(phdl, cluster_dict, config_dict, request):
    '''Run the ANC group "hbm_lvl3".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_groups(
        phdl,
        cluster_dict,
        config_dict,
        ["hbm_lvl3"],
        "test_hbm_lvl3",
        request=request,
    )


def test_hbm_lvl4(phdl, cluster_dict, config_dict, request):
    '''Run the ANC group "hbm_lvl4".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_groups(
        phdl,
        cluster_dict,
        config_dict,
        ["hbm_lvl4"],
        "test_hbm_lvl4",
        request=request,
    )


def test_hbm_lvl5(phdl, cluster_dict, config_dict, request):
    '''Run the ANC group "hbm_lvl5".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_groups(
        phdl,
        cluster_dict,
        config_dict,
        ["hbm_lvl5"],
        "test_hbm_lvl5",
        request=request,
    )
