'''
Copyright 2025 Advanced Micro Devices, Inc.
All rights reserved. This notice is intended as a precaution against inadvertent
publication and does not imply publication or any waiver of confidentiality.
The year included in the foregoing notice is the year of creation of the work.
All code contained here is Property of Advanced Micro Devices, Inc.
'''

'''
AUTO-GENERATED by build_tools/gen_anc_suites.py
Do NOT edit by hand. ANC single-group suite for the "hbm_lvl2" group (gpu).

Edit the group lists in cvs/lib/anc_lib.py and re-run
``make gen-anc-suites`` to regenerate. Installs/verifies ANC and fixes ROCm
ldconfig as pre-tasks, then runs the "hbm_lvl2" group; logs go to
{runner_log_folder}/anc_logs/<node>/test_hbm_lvl2/<timestamp>.
'''

from cvs.lib.anc_lib import AncGroupTest


class TestAncHbmLvl2(AncGroupTest):
    '''Run the single ANC group "hbm_lvl2".'''

    GROUP = "hbm_lvl2"
