'''
Copyright 2025 Advanced Micro Devices, Inc.
All rights reserved. This notice is intended as a precaution against inadvertent
publication and does not imply publication or any waiver of confidentiality.
The year included in the foregoing notice is the year of creation of the work.
All code contained here is Property of Advanced Micro Devices, Inc.

AUTO-GENERATED by build_tools/gen_anc_suites.py
Do NOT edit by hand. ANC CPU group suite: one ``test_<group>``
function per ANC group.

Edit the group/item lists in cvs/lib/anc_lib.py and re-run
``make gen-anc-suites`` to regenerate. Each function ensures ANC is installed
and ROCm ldconfig is fixed (session-cached via anc_lib.ensure_anc_ready), then
runs its one group; logs go to
{runner_log_folder}/anc_logs/<node>/test_<group>/<timestamp>.

Run every group:    cvs run anc_test_cpu ...
Run a single group: cvs run anc_test_cpu test_<group> ...
List the groups:    cvs list anc_test_cpu
'''

from cvs.lib import anc_lib


def test_cpu_content_check(phdl, cluster_dict, config_dict, request):
    '''Run the ANC group "cpu_content_check".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_groups(
        phdl,
        cluster_dict,
        config_dict,
        ["cpu_content_check"],
        "test_cpu_content_check",
        request=request,
    )


def test_cpu_mfg_l10(phdl, cluster_dict, config_dict, request):
    '''Run the ANC group "cpu_mfg_l10".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_groups(
        phdl,
        cluster_dict,
        config_dict,
        ["cpu_mfg_l10"],
        "test_cpu_mfg_l10",
        request=request,
    )


def test_weighted_sanity(phdl, cluster_dict, config_dict, request):
    '''Run the ANC group "weighted_sanity".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_groups(
        phdl,
        cluster_dict,
        config_dict,
        ["weighted_sanity"],
        "test_weighted_sanity",
        request=request,
    )


def test_dimm_content_check(phdl, cluster_dict, config_dict, request):
    '''Run the ANC group "dimm_content_check".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_groups(
        phdl,
        cluster_dict,
        config_dict,
        ["dimm_content_check"],
        "test_dimm_content_check",
        request=request,
    )


def test_dimm_mfg_l10(phdl, cluster_dict, config_dict, request):
    '''Run the ANC group "dimm_mfg_l10".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_groups(
        phdl,
        cluster_dict,
        config_dict,
        ["dimm_mfg_l10"],
        "test_dimm_mfg_l10",
        request=request,
    )


def test_dimm_weighted_sanity(phdl, cluster_dict, config_dict, request):
    '''Run the ANC group "dimm_weighted_sanity".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_groups(
        phdl,
        cluster_dict,
        config_dict,
        ["dimm_weighted_sanity"],
        "test_dimm_weighted_sanity",
        request=request,
    )
