'''
Copyright 2025 Advanced Micro Devices, Inc.
All rights reserved. This notice is intended as a precaution against inadvertent
publication and does not imply publication or any waiver of confidentiality.
The year included in the foregoing notice is the year of creation of the work.
All code contained here is Property of Advanced Micro Devices, Inc.

AUTO-GENERATED by build_tools/gen_anc_suites.py
Do NOT edit by hand. ANC CPU group suite: one ``test_<group>``
function per ANC cpu group.

Edit CPU_GROUPS / GPU_GROUPS in cvs/lib/anc_lib.py and re-run
``make gen-anc-suites`` to regenerate. Each function ensures ANC is installed
and ROCm ldconfig is fixed (session-cached via anc_lib.ensure_anc_ready), then
runs its one group; logs go to
{runner_log_folder}/anc_logs/<node>/test_<group>/<timestamp>.

Run every cpu group:  cvs run anc_test_cpu ...
Run a single group:      cvs run anc_test_cpu test_<group> ...
List the groups:         cvs list anc_test_cpu
'''

from cvs.lib import anc_lib


def test_ampttk_full(phdl, cluster_dict, config_dict, request):
    '''Run the ANC group "ampttk_full".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_groups(
        phdl,
        cluster_dict,
        config_dict,
        ["ampttk_full"],
        "test_ampttk_full",
        request=request,
    )


def test_cachewalker_full(phdl, cluster_dict, config_dict, request):
    '''Run the ANC group "cachewalker_full".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_groups(
        phdl,
        cluster_dict,
        config_dict,
        ["cachewalker_full"],
        "test_cachewalker_full",
        request=request,
    )


def test_cpu_all(phdl, cluster_dict, config_dict, request):
    '''Run the ANC group "cpu_all".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_groups(
        phdl,
        cluster_dict,
        config_dict,
        ["cpu_all"],
        "test_cpu_all",
        request=request,
    )


def test_cpu_content_check(phdl, cluster_dict, config_dict, request):
    '''Run the ANC group "cpu_content_check".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_groups(
        phdl,
        cluster_dict,
        config_dict,
        ["cpu_content_check"],
        "test_cpu_content_check",
        request=request,
    )


def test_cpu_mfg_l10(phdl, cluster_dict, config_dict, request):
    '''Run the ANC group "cpu_mfg_l10".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_groups(
        phdl,
        cluster_dict,
        config_dict,
        ["cpu_mfg_l10"],
        "test_cpu_mfg_l10",
        request=request,
    )


def test_cpu_sanity(phdl, cluster_dict, config_dict, request):
    '''Run the ANC group "cpu_sanity".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_groups(
        phdl,
        cluster_dict,
        config_dict,
        ["cpu_sanity"],
        "test_cpu_sanity",
        request=request,
    )


def test_difect_full(phdl, cluster_dict, config_dict, request):
    '''Run the ANC group "difect_full".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_groups(
        phdl,
        cluster_dict,
        config_dict,
        ["difect_full"],
        "test_difect_full",
        request=request,
    )


def test_fpdeluge_full(phdl, cluster_dict, config_dict, request):
    '''Run the ANC group "fpdeluge_full".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_groups(
        phdl,
        cluster_dict,
        config_dict,
        ["fpdeluge_full"],
        "test_fpdeluge_full",
        request=request,
    )


def test_hdrt_full(phdl, cluster_dict, config_dict, request):
    '''Run the ANC group "hdrt_full".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_groups(
        phdl,
        cluster_dict,
        config_dict,
        ["hdrt_full"],
        "test_hdrt_full",
        request=request,
    )


def test_maxcorestim_full(phdl, cluster_dict, config_dict, request):
    '''Run the ANC group "maxcorestim_full".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_groups(
        phdl,
        cluster_dict,
        config_dict,
        ["maxcorestim_full"],
        "test_maxcorestim_full",
        request=request,
    )


def test_memtest_full(phdl, cluster_dict, config_dict, request):
    '''Run the ANC group "memtest_full".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_groups(
        phdl,
        cluster_dict,
        config_dict,
        ["memtest_full"],
        "test_memtest_full",
        request=request,
    )


def test_miidct_full(phdl, cluster_dict, config_dict, request):
    '''Run the ANC group "miidct_full".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_groups(
        phdl,
        cluster_dict,
        config_dict,
        ["miidct_full"],
        "test_miidct_full",
        request=request,
    )


def test_mithac_full(phdl, cluster_dict, config_dict, request):
    '''Run the ANC group "mithac_full".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_groups(
        phdl,
        cluster_dict,
        config_dict,
        ["mithac_full"],
        "test_mithac_full",
        request=request,
    )


def test_weighted_sanity(phdl, cluster_dict, config_dict, request):
    '''Run the ANC group "weighted_sanity".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_groups(
        phdl,
        cluster_dict,
        config_dict,
        ["weighted_sanity"],
        "test_weighted_sanity",
        request=request,
    )
