'''
Copyright 2025 Advanced Micro Devices, Inc.
All rights reserved. This notice is intended as a precaution against inadvertent
publication and does not imply publication or any waiver of confidentiality.
The year included in the foregoing notice is the year of creation of the work.
All code contained here is Property of Advanced Micro Devices, Inc.

AUTO-GENERATED by build_tools/gen_anc_suites.py
Do NOT edit by hand. ANC MemRocker item suite: one ``test_<item>``
function per ANC item.

Edit the group/item lists in cvs/lib/anc_lib.py and re-run
``make gen-anc-suites`` to regenerate. Each function ensures ANC is installed
and ROCm ldconfig is fixed (session-cached via anc_lib.ensure_anc_ready), then
runs its one item; logs go to
{runner_log_folder}/anc_logs/<node>/test_<item>/<timestamp>.

Run every item:    cvs run anc_test_memrocker ...
Run a single item: cvs run anc_test_memrocker test_<item> ...
List the items:    cvs list anc_test_memrocker
'''

from cvs.lib import anc_lib


def test_memrocker_1002_6(orch, cluster_dict, config_dict, request):
    '''Run the ANC item "memrocker_1002_6".'''
    anc_lib.ensure_anc_ready(orch, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        orch,
        cluster_dict,
        config_dict,
        ["memrocker_1002_6"],
        "test_memrocker_1002_6",
        request=request,
    )


def test_memrocker_2_2(orch, cluster_dict, config_dict, request):
    '''Run the ANC item "memrocker_2_2".'''
    anc_lib.ensure_anc_ready(orch, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        orch,
        cluster_dict,
        config_dict,
        ["memrocker_2_2"],
        "test_memrocker_2_2",
        request=request,
    )


def test_memrocker_3_1(orch, cluster_dict, config_dict, request):
    '''Run the ANC item "memrocker_3_1".'''
    anc_lib.ensure_anc_ready(orch, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        orch,
        cluster_dict,
        config_dict,
        ["memrocker_3_1"],
        "test_memrocker_3_1",
        request=request,
    )


def test_memrocker_405_16(orch, cluster_dict, config_dict, request):
    '''Run the ANC item "memrocker_405_16".'''
    anc_lib.ensure_anc_ready(orch, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        orch,
        cluster_dict,
        config_dict,
        ["memrocker_405_16"],
        "test_memrocker_405_16",
        request=request,
    )


def test_memrocker_405_17(orch, cluster_dict, config_dict, request):
    '''Run the ANC item "memrocker_405_17".'''
    anc_lib.ensure_anc_ready(orch, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        orch,
        cluster_dict,
        config_dict,
        ["memrocker_405_17"],
        "test_memrocker_405_17",
        request=request,
    )


def test_memrocker_405_18(orch, cluster_dict, config_dict, request):
    '''Run the ANC item "memrocker_405_18".'''
    anc_lib.ensure_anc_ready(orch, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        orch,
        cluster_dict,
        config_dict,
        ["memrocker_405_18"],
        "test_memrocker_405_18",
        request=request,
    )


def test_memrocker_405_20(orch, cluster_dict, config_dict, request):
    '''Run the ANC item "memrocker_405_20".'''
    anc_lib.ensure_anc_ready(orch, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        orch,
        cluster_dict,
        config_dict,
        ["memrocker_405_20"],
        "test_memrocker_405_20",
        request=request,
    )


def test_memrocker_407_2(orch, cluster_dict, config_dict, request):
    '''Run the ANC item "memrocker_407_2".'''
    anc_lib.ensure_anc_ready(orch, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        orch,
        cluster_dict,
        config_dict,
        ["memrocker_407_2"],
        "test_memrocker_407_2",
        request=request,
    )


def test_memrocker_700_1(orch, cluster_dict, config_dict, request):
    '''Run the ANC item "memrocker_700_1".'''
    anc_lib.ensure_anc_ready(orch, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        orch,
        cluster_dict,
        config_dict,
        ["memrocker_700_1"],
        "test_memrocker_700_1",
        request=request,
    )


def test_memrocker_700_2(orch, cluster_dict, config_dict, request):
    '''Run the ANC item "memrocker_700_2".'''
    anc_lib.ensure_anc_ready(orch, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        orch,
        cluster_dict,
        config_dict,
        ["memrocker_700_2"],
        "test_memrocker_700_2",
        request=request,
    )
