#!/usr/bin/env python3
'''
Copyright 2025 Advanced Micro Devices, Inc.
All rights reserved. This notice is intended as a precaution against inadvertent
publication and does not imply publication or any waiver of confidentiality.
The year included in the foregoing notice is the year of creation of the work.
All code contained here is Property of Advanced Micro Devices, Inc.
'''

'''
Generate the per-group ANC suite files from the single source of truth
(cvs.lib.anc_lib.CPU_GROUPS / GPU_GROUPS).

Each ANC group gets its own committed suite file so it appears as a standalone
suite in ``cvs list`` and is runnable as ``cvs run anc_test_<group>``. The files
are thin subclasses of anc_lib.AncGroupTest and must NOT be hand-edited — edit
the group lists in anc_lib.py and re-run this generator:

    make gen-anc-suites        # or: python build_tools/gen_anc_suites.py

The generator is idempotent: it (re)writes exactly the files for the current
group lists and prunes stale generated files whose group no longer exists.
'''

import os
import sys

# Make the in-repo cvs importable without requiring an install.
REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if REPO_ROOT not in sys.path:
    sys.path.insert(0, REPO_ROOT)

from cvs.lib.anc_lib import (  # noqa: E402
    CPU_GROUPS,
    GPU_GROUPS,
    anc_group_class_name,
)

ANC_TESTS_DIR = os.path.join(REPO_ROOT, "cvs", "tests", "anc")

# Marker so we only ever prune files this generator produced.
GENERATED_MARKER = "AUTO-GENERATED by build_tools/gen_anc_suites.py"

_FILE_TEMPLATE = '''\
\'\'\'
Copyright 2025 Advanced Micro Devices, Inc.
All rights reserved. This notice is intended as a precaution against inadvertent
publication and does not imply publication or any waiver of confidentiality.
The year included in the foregoing notice is the year of creation of the work.
All code contained here is Property of Advanced Micro Devices, Inc.
\'\'\'

\'\'\'
{marker}
Do NOT edit by hand. ANC single-group suite for the "{group}" group ({kind}).

Edit the group lists in cvs/lib/anc_lib.py and re-run
``make gen-anc-suites`` to regenerate. Installs/verifies ANC and fixes ROCm
ldconfig as pre-tasks, then runs the "{group}" group; logs go to
{{runner_log_folder}}/anc_logs/<node>/test_{group}/<timestamp>.
\'\'\'

from cvs.lib.anc_lib import AncGroupTest


class TestAnc{cls}(AncGroupTest):
    \'\'\'Run the single ANC group "{group}".\'\'\'

    GROUP = "{group}"
'''

_INIT_TEMPLATE = '''\
\'\'\'
{marker}
Package marker for generated per-group ANC {kind} suites.
\'\'\'
'''


def _write(path, content):
    with open(path, "w") as fh:
        fh.write(content)
    print(f"wrote {os.path.relpath(path, REPO_ROOT)}")


def _prune_stale(subdir, keep_filenames):
    '''Remove generated .py files in subdir not in keep_filenames.'''
    for name in os.listdir(subdir):
        if not name.endswith(".py") or name in keep_filenames:
            continue
        path = os.path.join(subdir, name)
        try:
            # Read the whole (tiny) file: the marker sits in the second
            # docstring, past byte 360, so a small fixed read would miss it.
            with open(path) as fh:
                content = fh.read()
        except OSError:
            continue
        if GENERATED_MARKER in content:
            os.remove(path)
            print(f"pruned {os.path.relpath(path, REPO_ROOT)}")


def generate():
    for kind, groups in (("cpu", CPU_GROUPS), ("gpu", GPU_GROUPS)):
        subdir = os.path.join(ANC_TESTS_DIR, kind)
        os.makedirs(subdir, exist_ok=True)

        _write(
            os.path.join(subdir, "__init__.py"),
            _INIT_TEMPLATE.format(marker=GENERATED_MARKER, kind=kind),
        )

        keep = {"__init__.py"}
        for group in groups:
            filename = f"anc_test_{group}.py"
            keep.add(filename)
            _write(
                os.path.join(subdir, filename),
                _FILE_TEMPLATE.format(
                    marker=GENERATED_MARKER,
                    group=group,
                    kind=kind,
                    cls=anc_group_class_name(group),
                ),
            )

        _prune_stale(subdir, keep)


if __name__ == "__main__":
    generate()
    print("ANC per-group suites generated.")
