'''
Copyright 2025 Advanced Micro Devices, Inc.
All rights reserved. This notice is intended as a precaution against inadvertent
publication and does not imply publication or any waiver of confidentiality.
The year included in the foregoing notice is the year of creation of the work.
All code contained here is Property of Advanced Micro Devices, Inc.

AUTO-GENERATED by build_tools/gen_anc_suites.py
Do NOT edit by hand. ANC XGMI item suite: one ``test_<item>``
function per ANC item.

Edit the group/item lists in cvs/lib/anc_lib.py and re-run
``make gen-anc-suites`` to regenerate. Each function ensures ANC is installed
and ROCm ldconfig is fixed (session-cached via anc_lib.ensure_anc_ready), then
runs its one item; logs go to
{runner_log_folder}/anc_logs/<node>/test_<item>/<timestamp>.

Run every item:    cvs run anc_test_xgmi ...
Run a single item: cvs run anc_test_xgmi test_<item> ...
List the items:    cvs list anc_test_xgmi
'''

from cvs.lib import anc_lib


def test_xgmi_cpu_rx_margin(orch, cluster_dict, config_dict, request):
    '''Run the ANC item "xgmi_cpu_rx_margin".'''
    anc_lib.ensure_anc_ready(orch, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        orch,
        cluster_dict,
        config_dict,
        ["xgmi_cpu_rx_margin"],
        "test_xgmi_cpu_rx_margin",
        request=request,
    )


def test_xgmi_gpu_rx_margin(orch, cluster_dict, config_dict, request):
    '''Run the ANC item "xgmi_gpu_rx_margin".'''
    anc_lib.ensure_anc_ready(orch, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        orch,
        cluster_dict,
        config_dict,
        ["xgmi_gpu_rx_margin"],
        "test_xgmi_gpu_rx_margin",
        request=request,
    )


def test_xgmi_link_status(orch, cluster_dict, config_dict, request):
    '''Run the ANC item "xgmi_link_status".'''
    anc_lib.ensure_anc_ready(orch, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        orch,
        cluster_dict,
        config_dict,
        ["xgmi_link_status"],
        "test_xgmi_link_status",
        request=request,
    )
