gpu_nodes:
  hosts:
  - ctheliosr-rck-g02-j19-4.rck.dcgpu
  - ctheliosr-rck-g02-j19-5.rck.dcgpu
  - ctheliosr-rck-g02-j19-6.rck.dcgpu
  - ctheliosr-rck-g02-j19-8.rck.dcgpu
  - ctheliosr-rck-g02-j19-18.rck.dcgpu
  - ctheliosr-rck-g02-j19-12.rck.dcgpu
  - ctheliosr-rck-g02-j19-13.rck.dcgpu
  - ctheliosr-rck-g02-j19-14.rck.dcgpu
  - ctheliosr-rck-g02-j19-15.rck.dcgpu
  - ctheliosr-rck-g02-j19-17.rck.dcgpu
  - ctheliosr-rck-g02-j19-18.rck.dcgpu
  jump_host:
    auth_method: key
    enabled: false
    host: ''
    key_file: ~/.ssh/id_rsa
    username: root
  ssh:
    auth_method: key
    key_file: /root/.ssh/id_rsa.pem
    timeout: 30
    username: venksrin
poll_interval: 120
scale_out_switches:
  hosts: []
  jump_host:
    auth_method: key
    enabled: false
    host: ''
    key_file: ~/.ssh/id_rsa
    username: root
  ssh:
    auth_method: key
    key_file: ~/.ssh/id_rsa
    timeout: 30
    username: root
scale_up_switches:
  hosts:
  - 10.190.192.124
  - 10.190.192.132
  jump_host:
    auth_method: key
    enabled: false
    host: ''
    key_file: ~/.ssh/id_rsa
    username: root
  ssh:
    auth_method: password
    key_file: ~/.ssh/id_rsa
    timeout: 30
    username: admin
