compute_ssh:
  auth_method: password
  key_file: null
  timeout: 30
  username: amd
compute_trays:
- ctheliosp-rck-g02-H21-15.rck.dcgpu
- ctheliosp-rck-g02-H21-17.rck.dcgpu
- ctheliosp-rck-g02-H21-18.rck.dcgpu
- ctheliosp-rck-g02-H21-6.rck.dcgpu
- ctheliosp-rck-g02-H21-7.rck.dcgpu
- ctheliosp-rck-g02-H21-9.rck.dcgpu
poll_interval: 120
switch_ssh:
  auth_method: password
  key_file: null
  timeout: 30
  username: admin
switch_trays:
- 10.190.192.124
- 10.190.192.132
- 10.190.192.154
- 10.190.192.133
- 10.190.192.12
- 10.190.192.134
