'''
Copyright 2025 Advanced Micro Devices, Inc.
All rights reserved. This notice is intended as a precaution against inadvertent
publication and does not imply publication or any waiver of confidentiality.
The year included in the foregoing notice is the year of creation of the work.
All code contained here is Property of Advanced Micro Devices, Inc.

AUTO-GENERATED by build_tools/gen_anc_suites.py
Do NOT edit by hand. ANC ComputeRocker item suite: one ``test_<item>``
function per ANC item.

Edit the group/item lists in cvs/lib/anc_lib.py and re-run
``make gen-anc-suites`` to regenerate. Each function ensures ANC is installed
and ROCm ldconfig is fixed (session-cached via anc_lib.ensure_anc_ready), then
runs its one item; logs go to
{runner_log_folder}/anc_logs/<node>/test_<item>/<timestamp>.

Run every item:    cvs run anc_test_computerocker ...
Run a single item: cvs run anc_test_computerocker test_<item> ...
List the items:    cvs list anc_test_computerocker
'''

from cvs.lib import anc_lib


def test_computerocker_dist001_000(orch, cluster_dict, config_dict, request):
    '''Run the ANC item "computerocker_dist001_000".'''
    anc_lib.ensure_anc_ready(orch, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        orch,
        cluster_dict,
        config_dict,
        ["computerocker_dist001_000"],
        "test_computerocker_dist001_000",
        request=request,
    )


def test_computerocker_dist001_001(orch, cluster_dict, config_dict, request):
    '''Run the ANC item "computerocker_dist001_001".'''
    anc_lib.ensure_anc_ready(orch, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        orch,
        cluster_dict,
        config_dict,
        ["computerocker_dist001_001"],
        "test_computerocker_dist001_001",
        request=request,
    )


def test_computerocker_dist001_002(orch, cluster_dict, config_dict, request):
    '''Run the ANC item "computerocker_dist001_002".'''
    anc_lib.ensure_anc_ready(orch, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        orch,
        cluster_dict,
        config_dict,
        ["computerocker_dist001_002"],
        "test_computerocker_dist001_002",
        request=request,
    )


def test_computerocker_dist001_003(orch, cluster_dict, config_dict, request):
    '''Run the ANC item "computerocker_dist001_003".'''
    anc_lib.ensure_anc_ready(orch, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        orch,
        cluster_dict,
        config_dict,
        ["computerocker_dist001_003"],
        "test_computerocker_dist001_003",
        request=request,
    )


def test_computerocker_dist001_004(orch, cluster_dict, config_dict, request):
    '''Run the ANC item "computerocker_dist001_004".'''
    anc_lib.ensure_anc_ready(orch, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        orch,
        cluster_dict,
        config_dict,
        ["computerocker_dist001_004"],
        "test_computerocker_dist001_004",
        request=request,
    )


def test_computerocker_dist001_005(orch, cluster_dict, config_dict, request):
    '''Run the ANC item "computerocker_dist001_005".'''
    anc_lib.ensure_anc_ready(orch, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        orch,
        cluster_dict,
        config_dict,
        ["computerocker_dist001_005"],
        "test_computerocker_dist001_005",
        request=request,
    )


def test_computerocker_dist001_006(orch, cluster_dict, config_dict, request):
    '''Run the ANC item "computerocker_dist001_006".'''
    anc_lib.ensure_anc_ready(orch, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        orch,
        cluster_dict,
        config_dict,
        ["computerocker_dist001_006"],
        "test_computerocker_dist001_006",
        request=request,
    )


def test_computerocker_dist001_007(orch, cluster_dict, config_dict, request):
    '''Run the ANC item "computerocker_dist001_007".'''
    anc_lib.ensure_anc_ready(orch, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        orch,
        cluster_dict,
        config_dict,
        ["computerocker_dist001_007"],
        "test_computerocker_dist001_007",
        request=request,
    )


def test_computerocker_dist001_008(orch, cluster_dict, config_dict, request):
    '''Run the ANC item "computerocker_dist001_008".'''
    anc_lib.ensure_anc_ready(orch, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        orch,
        cluster_dict,
        config_dict,
        ["computerocker_dist001_008"],
        "test_computerocker_dist001_008",
        request=request,
    )


def test_computerocker_dist001_009(orch, cluster_dict, config_dict, request):
    '''Run the ANC item "computerocker_dist001_009".'''
    anc_lib.ensure_anc_ready(orch, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        orch,
        cluster_dict,
        config_dict,
        ["computerocker_dist001_009"],
        "test_computerocker_dist001_009",
        request=request,
    )


def test_computerocker_dist001_010(orch, cluster_dict, config_dict, request):
    '''Run the ANC item "computerocker_dist001_010".'''
    anc_lib.ensure_anc_ready(orch, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        orch,
        cluster_dict,
        config_dict,
        ["computerocker_dist001_010"],
        "test_computerocker_dist001_010",
        request=request,
    )


def test_computerocker_dist002_000(orch, cluster_dict, config_dict, request):
    '''Run the ANC item "computerocker_dist002_000".'''
    anc_lib.ensure_anc_ready(orch, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        orch,
        cluster_dict,
        config_dict,
        ["computerocker_dist002_000"],
        "test_computerocker_dist002_000",
        request=request,
    )


def test_computerocker_dist002_001(orch, cluster_dict, config_dict, request):
    '''Run the ANC item "computerocker_dist002_001".'''
    anc_lib.ensure_anc_ready(orch, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        orch,
        cluster_dict,
        config_dict,
        ["computerocker_dist002_001"],
        "test_computerocker_dist002_001",
        request=request,
    )


def test_computerocker_dist002_002(orch, cluster_dict, config_dict, request):
    '''Run the ANC item "computerocker_dist002_002".'''
    anc_lib.ensure_anc_ready(orch, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        orch,
        cluster_dict,
        config_dict,
        ["computerocker_dist002_002"],
        "test_computerocker_dist002_002",
        request=request,
    )


def test_computerocker_dist002_003(orch, cluster_dict, config_dict, request):
    '''Run the ANC item "computerocker_dist002_003".'''
    anc_lib.ensure_anc_ready(orch, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        orch,
        cluster_dict,
        config_dict,
        ["computerocker_dist002_003"],
        "test_computerocker_dist002_003",
        request=request,
    )


def test_computerocker_dist002_004(orch, cluster_dict, config_dict, request):
    '''Run the ANC item "computerocker_dist002_004".'''
    anc_lib.ensure_anc_ready(orch, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        orch,
        cluster_dict,
        config_dict,
        ["computerocker_dist002_004"],
        "test_computerocker_dist002_004",
        request=request,
    )


def test_computerocker_dist002_005(orch, cluster_dict, config_dict, request):
    '''Run the ANC item "computerocker_dist002_005".'''
    anc_lib.ensure_anc_ready(orch, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        orch,
        cluster_dict,
        config_dict,
        ["computerocker_dist002_005"],
        "test_computerocker_dist002_005",
        request=request,
    )


def test_computerocker_dist002_006(orch, cluster_dict, config_dict, request):
    '''Run the ANC item "computerocker_dist002_006".'''
    anc_lib.ensure_anc_ready(orch, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        orch,
        cluster_dict,
        config_dict,
        ["computerocker_dist002_006"],
        "test_computerocker_dist002_006",
        request=request,
    )


def test_computerocker_dist002_007(orch, cluster_dict, config_dict, request):
    '''Run the ANC item "computerocker_dist002_007".'''
    anc_lib.ensure_anc_ready(orch, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        orch,
        cluster_dict,
        config_dict,
        ["computerocker_dist002_007"],
        "test_computerocker_dist002_007",
        request=request,
    )


def test_computerocker_dist002_008(orch, cluster_dict, config_dict, request):
    '''Run the ANC item "computerocker_dist002_008".'''
    anc_lib.ensure_anc_ready(orch, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        orch,
        cluster_dict,
        config_dict,
        ["computerocker_dist002_008"],
        "test_computerocker_dist002_008",
        request=request,
    )


def test_computerocker_dist002_009(orch, cluster_dict, config_dict, request):
    '''Run the ANC item "computerocker_dist002_009".'''
    anc_lib.ensure_anc_ready(orch, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        orch,
        cluster_dict,
        config_dict,
        ["computerocker_dist002_009"],
        "test_computerocker_dist002_009",
        request=request,
    )


def test_computerocker_msa001_001(orch, cluster_dict, config_dict, request):
    '''Run the ANC item "computerocker_msa001_001".'''
    anc_lib.ensure_anc_ready(orch, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        orch,
        cluster_dict,
        config_dict,
        ["computerocker_msa001_001"],
        "test_computerocker_msa001_001",
        request=request,
    )


def test_computerocker_msa001_002(orch, cluster_dict, config_dict, request):
    '''Run the ANC item "computerocker_msa001_002".'''
    anc_lib.ensure_anc_ready(orch, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        orch,
        cluster_dict,
        config_dict,
        ["computerocker_msa001_002"],
        "test_computerocker_msa001_002",
        request=request,
    )


def test_computerocker_msa001_003(orch, cluster_dict, config_dict, request):
    '''Run the ANC item "computerocker_msa001_003".'''
    anc_lib.ensure_anc_ready(orch, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        orch,
        cluster_dict,
        config_dict,
        ["computerocker_msa001_003"],
        "test_computerocker_msa001_003",
        request=request,
    )
