'''
Copyright 2025 Advanced Micro Devices, Inc.
All rights reserved. This notice is intended as a precaution against inadvertent
publication and does not imply publication or any waiver of confidentiality.
The year included in the foregoing notice is the year of creation of the work.
All code contained here is Property of Advanced Micro Devices, Inc.

AUTO-GENERATED by build_tools/gen_anc_suites.py
Do NOT edit by hand. ANC basic item suite: one ``test_<item>``
function per ANC item.

Edit the group/item lists in cvs/lib/anc_lib.py and re-run
``make gen-anc-suites`` to regenerate. Each function ensures ANC is installed
and ROCm ldconfig is fixed (session-cached via anc_lib.ensure_anc_ready), then
runs its one item; logs go to
{runner_log_folder}/anc_logs/<node>/test_<item>/<timestamp>.

Run every item:    cvs run anc_test_basic ...
Run a single item: cvs run anc_test_basic test_<item> ...
List the items:    cvs list anc_test_basic
'''

from cvs.lib import anc_lib


def test_ampttk(phdl, cluster_dict, config_dict, request):
    '''Run the ANC item "ampttk".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        phdl,
        cluster_dict,
        config_dict,
        ["ampttk"],
        "test_ampttk",
        request=request,
    )


def test_cachewalker(phdl, cluster_dict, config_dict, request):
    '''Run the ANC item "cachewalker".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        phdl,
        cluster_dict,
        config_dict,
        ["cachewalker"],
        "test_cachewalker",
        request=request,
    )


def test_cpu_bidi_peak(phdl, cluster_dict, config_dict, request):
    '''Run the ANC item "cpu_bidi_peak".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        phdl,
        cluster_dict,
        config_dict,
        ["cpu_bidi_peak"],
        "test_cpu_bidi_peak",
        request=request,
    )


def test_difect(phdl, cluster_dict, config_dict, request):
    '''Run the ANC item "difect".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        phdl,
        cluster_dict,
        config_dict,
        ["difect"],
        "test_difect",
        request=request,
    )


def test_fpdeluge(phdl, cluster_dict, config_dict, request):
    '''Run the ANC item "fpdeluge".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        phdl,
        cluster_dict,
        config_dict,
        ["fpdeluge"],
        "test_fpdeluge",
        request=request,
    )


def test_gfx_bidi_peak(phdl, cluster_dict, config_dict, request):
    '''Run the ANC item "gfx_bidi_peak".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        phdl,
        cluster_dict,
        config_dict,
        ["gfx_bidi_peak"],
        "test_gfx_bidi_peak",
        request=request,
    )


def test_hdrt(phdl, cluster_dict, config_dict, request):
    '''Run the ANC item "hdrt".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        phdl,
        cluster_dict,
        config_dict,
        ["hdrt"],
        "test_hdrt",
        request=request,
    )


def test_maxcorestim(phdl, cluster_dict, config_dict, request):
    '''Run the ANC item "maxcorestim".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        phdl,
        cluster_dict,
        config_dict,
        ["maxcorestim"],
        "test_maxcorestim",
        request=request,
    )


def test_maxiostim(phdl, cluster_dict, config_dict, request):
    '''Run the ANC item "maxiostim".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        phdl,
        cluster_dict,
        config_dict,
        ["maxiostim"],
        "test_maxiostim",
        request=request,
    )


def test_memblock(phdl, cluster_dict, config_dict, request):
    '''Run the ANC item "memblock".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        phdl,
        cluster_dict,
        config_dict,
        ["memblock"],
        "test_memblock",
        request=request,
    )


def test_memripper(phdl, cluster_dict, config_dict, request):
    '''Run the ANC item "memripper".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        phdl,
        cluster_dict,
        config_dict,
        ["memripper"],
        "test_memripper",
        request=request,
    )


def test_memtest(phdl, cluster_dict, config_dict, request):
    '''Run the ANC item "memtest".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        phdl,
        cluster_dict,
        config_dict,
        ["memtest"],
        "test_memtest",
        request=request,
    )


def test_miidct(phdl, cluster_dict, config_dict, request):
    '''Run the ANC item "miidct".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        phdl,
        cluster_dict,
        config_dict,
        ["miidct"],
        "test_miidct",
        request=request,
    )


def test_mithac(phdl, cluster_dict, config_dict, request):
    '''Run the ANC item "mithac".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        phdl,
        cluster_dict,
        config_dict,
        ["mithac"],
        "test_mithac",
        request=request,
    )


def test_no_op(phdl, cluster_dict, config_dict, request):
    '''Run the ANC item "no_op".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        phdl,
        cluster_dict,
        config_dict,
        ["no_op"],
        "test_no_op",
        request=request,
    )


def test_sdma_bidi_peak(phdl, cluster_dict, config_dict, request):
    '''Run the ANC item "sdma_bidi_peak".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        phdl,
        cluster_dict,
        config_dict,
        ["sdma_bidi_peak"],
        "test_sdma_bidi_peak",
        request=request,
    )


def test_sprites(phdl, cluster_dict, config_dict, request):
    '''Run the ANC item "sprites".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        phdl,
        cluster_dict,
        config_dict,
        ["sprites"],
        "test_sprites",
        request=request,
    )


def test_umcinfo(phdl, cluster_dict, config_dict, request):
    '''Run the ANC item "umcinfo".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        phdl,
        cluster_dict,
        config_dict,
        ["umcinfo"],
        "test_umcinfo",
        request=request,
    )
