'''
Copyright 2025 Advanced Micro Devices, Inc.
All rights reserved. This notice is intended as a precaution against inadvertent
publication and does not imply publication or any waiver of confidentiality.
The year included in the foregoing notice is the year of creation of the work.
All code contained here is Property of Advanced Micro Devices, Inc.

AUTO-GENERATED by build_tools/gen_anc_suites.py
Do NOT edit by hand. ANC Babel item suite: one ``test_<item>``
function per ANC item.

Edit the group/item lists in cvs/lib/anc_lib.py and re-run
``make gen-anc-suites`` to regenerate. Each function ensures ANC is installed
and ROCm ldconfig is fixed (session-cached via anc_lib.ensure_anc_ready), then
runs its one item; logs go to
{runner_log_folder}/anc_logs/<node>/test_<item>/<timestamp>.

Run every item:    cvs run anc_test_babel ...
Run a single item: cvs run anc_test_babel test_<item> ...
List the items:    cvs list anc_test_babel
'''

from cvs.lib import anc_lib


def test_babel_modinit_read(phdl, cluster_dict, config_dict, request):
    '''Run the ANC item "babel_modinit_read".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        phdl,
        cluster_dict,
        config_dict,
        ["babel_modinit_read"],
        "test_babel_modinit_read",
        request=request,
    )


def test_babel_modinit_triad(phdl, cluster_dict, config_dict, request):
    '''Run the ANC item "babel_modinit_triad".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        phdl,
        cluster_dict,
        config_dict,
        ["babel_modinit_triad"],
        "test_babel_modinit_triad",
        request=request,
    )
