'''
Copyright 2025 Advanced Micro Devices, Inc.
All rights reserved. This notice is intended as a precaution against inadvertent
publication and does not imply publication or any waiver of confidentiality.
The year included in the foregoing notice is the year of creation of the work.
All code contained here is Property of Advanced Micro Devices, Inc.

AUTO-GENERATED by build_tools/gen_anc_suites.py
Do NOT edit by hand. ANC individual item suite: one ``test_<item>``
function per ANC item.

Edit CPU_GROUPS / GPU_GROUPS / INDIVIDUAL_ITEMS in cvs/lib/anc_lib.py and re-run
``make gen-anc-suites`` to regenerate. Each function ensures ANC is installed
and ROCm ldconfig is fixed (session-cached via anc_lib.ensure_anc_ready), then
runs its one item; logs go to
{runner_log_folder}/anc_logs/<node>/test_<item>/<timestamp>.

Run every item:    cvs run anc_test_individual_items ...
Run a single item: cvs run anc_test_individual_items test_<item> ...
List the items:    cvs list anc_test_individual_items
'''

from cvs.lib import anc_lib


def test_ampttk(phdl, cluster_dict, config_dict, request):
    '''Run the ANC item "ampttk".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        phdl,
        cluster_dict,
        config_dict,
        ["ampttk"],
        "test_ampttk",
        request=request,
    )


def test_babel_modinit_read(phdl, cluster_dict, config_dict, request):
    '''Run the ANC item "babel_modinit_read".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        phdl,
        cluster_dict,
        config_dict,
        ["babel_modinit_read"],
        "test_babel_modinit_read",
        request=request,
    )


def test_babel_modinit_triad(phdl, cluster_dict, config_dict, request):
    '''Run the ANC item "babel_modinit_triad".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        phdl,
        cluster_dict,
        config_dict,
        ["babel_modinit_triad"],
        "test_babel_modinit_triad",
        request=request,
    )


def test_cachewalker(phdl, cluster_dict, config_dict, request):
    '''Run the ANC item "cachewalker".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        phdl,
        cluster_dict,
        config_dict,
        ["cachewalker"],
        "test_cachewalker",
        request=request,
    )


def test_computerocker_dist001_000(phdl, cluster_dict, config_dict, request):
    '''Run the ANC item "computerocker_dist001_000".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        phdl,
        cluster_dict,
        config_dict,
        ["computerocker_dist001_000"],
        "test_computerocker_dist001_000",
        request=request,
    )


def test_computerocker_dist001_001(phdl, cluster_dict, config_dict, request):
    '''Run the ANC item "computerocker_dist001_001".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        phdl,
        cluster_dict,
        config_dict,
        ["computerocker_dist001_001"],
        "test_computerocker_dist001_001",
        request=request,
    )


def test_computerocker_dist001_002(phdl, cluster_dict, config_dict, request):
    '''Run the ANC item "computerocker_dist001_002".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        phdl,
        cluster_dict,
        config_dict,
        ["computerocker_dist001_002"],
        "test_computerocker_dist001_002",
        request=request,
    )


def test_computerocker_dist001_003(phdl, cluster_dict, config_dict, request):
    '''Run the ANC item "computerocker_dist001_003".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        phdl,
        cluster_dict,
        config_dict,
        ["computerocker_dist001_003"],
        "test_computerocker_dist001_003",
        request=request,
    )


def test_computerocker_dist001_004(phdl, cluster_dict, config_dict, request):
    '''Run the ANC item "computerocker_dist001_004".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        phdl,
        cluster_dict,
        config_dict,
        ["computerocker_dist001_004"],
        "test_computerocker_dist001_004",
        request=request,
    )


def test_computerocker_dist001_005(phdl, cluster_dict, config_dict, request):
    '''Run the ANC item "computerocker_dist001_005".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        phdl,
        cluster_dict,
        config_dict,
        ["computerocker_dist001_005"],
        "test_computerocker_dist001_005",
        request=request,
    )


def test_computerocker_dist001_006(phdl, cluster_dict, config_dict, request):
    '''Run the ANC item "computerocker_dist001_006".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        phdl,
        cluster_dict,
        config_dict,
        ["computerocker_dist001_006"],
        "test_computerocker_dist001_006",
        request=request,
    )


def test_computerocker_dist001_007(phdl, cluster_dict, config_dict, request):
    '''Run the ANC item "computerocker_dist001_007".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        phdl,
        cluster_dict,
        config_dict,
        ["computerocker_dist001_007"],
        "test_computerocker_dist001_007",
        request=request,
    )


def test_computerocker_dist001_008(phdl, cluster_dict, config_dict, request):
    '''Run the ANC item "computerocker_dist001_008".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        phdl,
        cluster_dict,
        config_dict,
        ["computerocker_dist001_008"],
        "test_computerocker_dist001_008",
        request=request,
    )


def test_computerocker_dist001_009(phdl, cluster_dict, config_dict, request):
    '''Run the ANC item "computerocker_dist001_009".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        phdl,
        cluster_dict,
        config_dict,
        ["computerocker_dist001_009"],
        "test_computerocker_dist001_009",
        request=request,
    )


def test_computerocker_dist001_010(phdl, cluster_dict, config_dict, request):
    '''Run the ANC item "computerocker_dist001_010".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        phdl,
        cluster_dict,
        config_dict,
        ["computerocker_dist001_010"],
        "test_computerocker_dist001_010",
        request=request,
    )


def test_computerocker_dist002_000(phdl, cluster_dict, config_dict, request):
    '''Run the ANC item "computerocker_dist002_000".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        phdl,
        cluster_dict,
        config_dict,
        ["computerocker_dist002_000"],
        "test_computerocker_dist002_000",
        request=request,
    )


def test_computerocker_dist002_001(phdl, cluster_dict, config_dict, request):
    '''Run the ANC item "computerocker_dist002_001".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        phdl,
        cluster_dict,
        config_dict,
        ["computerocker_dist002_001"],
        "test_computerocker_dist002_001",
        request=request,
    )


def test_computerocker_dist002_002(phdl, cluster_dict, config_dict, request):
    '''Run the ANC item "computerocker_dist002_002".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        phdl,
        cluster_dict,
        config_dict,
        ["computerocker_dist002_002"],
        "test_computerocker_dist002_002",
        request=request,
    )


def test_computerocker_dist002_003(phdl, cluster_dict, config_dict, request):
    '''Run the ANC item "computerocker_dist002_003".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        phdl,
        cluster_dict,
        config_dict,
        ["computerocker_dist002_003"],
        "test_computerocker_dist002_003",
        request=request,
    )


def test_computerocker_dist002_004(phdl, cluster_dict, config_dict, request):
    '''Run the ANC item "computerocker_dist002_004".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        phdl,
        cluster_dict,
        config_dict,
        ["computerocker_dist002_004"],
        "test_computerocker_dist002_004",
        request=request,
    )


def test_computerocker_dist002_005(phdl, cluster_dict, config_dict, request):
    '''Run the ANC item "computerocker_dist002_005".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        phdl,
        cluster_dict,
        config_dict,
        ["computerocker_dist002_005"],
        "test_computerocker_dist002_005",
        request=request,
    )


def test_computerocker_dist002_006(phdl, cluster_dict, config_dict, request):
    '''Run the ANC item "computerocker_dist002_006".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        phdl,
        cluster_dict,
        config_dict,
        ["computerocker_dist002_006"],
        "test_computerocker_dist002_006",
        request=request,
    )


def test_computerocker_dist002_007(phdl, cluster_dict, config_dict, request):
    '''Run the ANC item "computerocker_dist002_007".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        phdl,
        cluster_dict,
        config_dict,
        ["computerocker_dist002_007"],
        "test_computerocker_dist002_007",
        request=request,
    )


def test_computerocker_dist002_008(phdl, cluster_dict, config_dict, request):
    '''Run the ANC item "computerocker_dist002_008".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        phdl,
        cluster_dict,
        config_dict,
        ["computerocker_dist002_008"],
        "test_computerocker_dist002_008",
        request=request,
    )


def test_computerocker_dist002_009(phdl, cluster_dict, config_dict, request):
    '''Run the ANC item "computerocker_dist002_009".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        phdl,
        cluster_dict,
        config_dict,
        ["computerocker_dist002_009"],
        "test_computerocker_dist002_009",
        request=request,
    )


def test_computerocker_msa001_001(phdl, cluster_dict, config_dict, request):
    '''Run the ANC item "computerocker_msa001_001".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        phdl,
        cluster_dict,
        config_dict,
        ["computerocker_msa001_001"],
        "test_computerocker_msa001_001",
        request=request,
    )


def test_computerocker_msa001_002(phdl, cluster_dict, config_dict, request):
    '''Run the ANC item "computerocker_msa001_002".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        phdl,
        cluster_dict,
        config_dict,
        ["computerocker_msa001_002"],
        "test_computerocker_msa001_002",
        request=request,
    )


def test_computerocker_msa001_003(phdl, cluster_dict, config_dict, request):
    '''Run the ANC item "computerocker_msa001_003".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        phdl,
        cluster_dict,
        config_dict,
        ["computerocker_msa001_003"],
        "test_computerocker_msa001_003",
        request=request,
    )


def test_cpu_bidi_peak(phdl, cluster_dict, config_dict, request):
    '''Run the ANC item "cpu_bidi_peak".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        phdl,
        cluster_dict,
        config_dict,
        ["cpu_bidi_peak"],
        "test_cpu_bidi_peak",
        request=request,
    )


def test_difect(phdl, cluster_dict, config_dict, request):
    '''Run the ANC item "difect".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        phdl,
        cluster_dict,
        config_dict,
        ["difect"],
        "test_difect",
        request=request,
    )


def test_fpdeluge(phdl, cluster_dict, config_dict, request):
    '''Run the ANC item "fpdeluge".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        phdl,
        cluster_dict,
        config_dict,
        ["fpdeluge"],
        "test_fpdeluge",
        request=request,
    )


def test_gemm_bf16_trig(phdl, cluster_dict, config_dict, request):
    '''Run the ANC item "gemm_bf16_trig".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        phdl,
        cluster_dict,
        config_dict,
        ["gemm_bf16_trig"],
        "test_gemm_bf16_trig",
        request=request,
    )


def test_gemm_fp16_trig(phdl, cluster_dict, config_dict, request):
    '''Run the ANC item "gemm_fp16_trig".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        phdl,
        cluster_dict,
        config_dict,
        ["gemm_fp16_trig"],
        "test_gemm_fp16_trig",
        request=request,
    )


def test_gemm_fp8_trig(phdl, cluster_dict, config_dict, request):
    '''Run the ANC item "gemm_fp8_trig".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        phdl,
        cluster_dict,
        config_dict,
        ["gemm_fp8_trig"],
        "test_gemm_fp8_trig",
        request=request,
    )


def test_gfx_bidi_peak(phdl, cluster_dict, config_dict, request):
    '''Run the ANC item "gfx_bidi_peak".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        phdl,
        cluster_dict,
        config_dict,
        ["gfx_bidi_peak"],
        "test_gfx_bidi_peak",
        request=request,
    )


def test_hdrt(phdl, cluster_dict, config_dict, request):
    '''Run the ANC item "hdrt".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        phdl,
        cluster_dict,
        config_dict,
        ["hdrt"],
        "test_hdrt",
        request=request,
    )


def test_maxcorestim(phdl, cluster_dict, config_dict, request):
    '''Run the ANC item "maxcorestim".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        phdl,
        cluster_dict,
        config_dict,
        ["maxcorestim"],
        "test_maxcorestim",
        request=request,
    )


def test_maxiostim(phdl, cluster_dict, config_dict, request):
    '''Run the ANC item "maxiostim".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        phdl,
        cluster_dict,
        config_dict,
        ["maxiostim"],
        "test_maxiostim",
        request=request,
    )


def test_memblock(phdl, cluster_dict, config_dict, request):
    '''Run the ANC item "memblock".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        phdl,
        cluster_dict,
        config_dict,
        ["memblock"],
        "test_memblock",
        request=request,
    )


def test_memripper(phdl, cluster_dict, config_dict, request):
    '''Run the ANC item "memripper".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        phdl,
        cluster_dict,
        config_dict,
        ["memripper"],
        "test_memripper",
        request=request,
    )


def test_memrocker_1002_6(phdl, cluster_dict, config_dict, request):
    '''Run the ANC item "memrocker_1002_6".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        phdl,
        cluster_dict,
        config_dict,
        ["memrocker_1002_6"],
        "test_memrocker_1002_6",
        request=request,
    )


def test_memrocker_2_2(phdl, cluster_dict, config_dict, request):
    '''Run the ANC item "memrocker_2_2".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        phdl,
        cluster_dict,
        config_dict,
        ["memrocker_2_2"],
        "test_memrocker_2_2",
        request=request,
    )


def test_memrocker_3_1(phdl, cluster_dict, config_dict, request):
    '''Run the ANC item "memrocker_3_1".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        phdl,
        cluster_dict,
        config_dict,
        ["memrocker_3_1"],
        "test_memrocker_3_1",
        request=request,
    )


def test_memrocker_405_16(phdl, cluster_dict, config_dict, request):
    '''Run the ANC item "memrocker_405_16".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        phdl,
        cluster_dict,
        config_dict,
        ["memrocker_405_16"],
        "test_memrocker_405_16",
        request=request,
    )


def test_memrocker_405_17(phdl, cluster_dict, config_dict, request):
    '''Run the ANC item "memrocker_405_17".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        phdl,
        cluster_dict,
        config_dict,
        ["memrocker_405_17"],
        "test_memrocker_405_17",
        request=request,
    )


def test_memrocker_405_18(phdl, cluster_dict, config_dict, request):
    '''Run the ANC item "memrocker_405_18".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        phdl,
        cluster_dict,
        config_dict,
        ["memrocker_405_18"],
        "test_memrocker_405_18",
        request=request,
    )


def test_memrocker_405_20(phdl, cluster_dict, config_dict, request):
    '''Run the ANC item "memrocker_405_20".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        phdl,
        cluster_dict,
        config_dict,
        ["memrocker_405_20"],
        "test_memrocker_405_20",
        request=request,
    )


def test_memrocker_407_2(phdl, cluster_dict, config_dict, request):
    '''Run the ANC item "memrocker_407_2".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        phdl,
        cluster_dict,
        config_dict,
        ["memrocker_407_2"],
        "test_memrocker_407_2",
        request=request,
    )


def test_memrocker_700_1(phdl, cluster_dict, config_dict, request):
    '''Run the ANC item "memrocker_700_1".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        phdl,
        cluster_dict,
        config_dict,
        ["memrocker_700_1"],
        "test_memrocker_700_1",
        request=request,
    )


def test_memrocker_700_2(phdl, cluster_dict, config_dict, request):
    '''Run the ANC item "memrocker_700_2".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        phdl,
        cluster_dict,
        config_dict,
        ["memrocker_700_2"],
        "test_memrocker_700_2",
        request=request,
    )


def test_memtest(phdl, cluster_dict, config_dict, request):
    '''Run the ANC item "memtest".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        phdl,
        cluster_dict,
        config_dict,
        ["memtest"],
        "test_memtest",
        request=request,
    )


def test_miidct(phdl, cluster_dict, config_dict, request):
    '''Run the ANC item "miidct".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        phdl,
        cluster_dict,
        config_dict,
        ["miidct"],
        "test_miidct",
        request=request,
    )


def test_mithac(phdl, cluster_dict, config_dict, request):
    '''Run the ANC item "mithac".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        phdl,
        cluster_dict,
        config_dict,
        ["mithac"],
        "test_mithac",
        request=request,
    )


def test_no_op(phdl, cluster_dict, config_dict, request):
    '''Run the ANC item "no_op".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        phdl,
        cluster_dict,
        config_dict,
        ["no_op"],
        "test_no_op",
        request=request,
    )


def test_oblex_ds(phdl, cluster_dict, config_dict, request):
    '''Run the ANC item "oblex_ds".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        phdl,
        cluster_dict,
        config_dict,
        ["oblex_ds"],
        "test_oblex_ds",
        request=request,
    )


def test_oblex_ds_ntd(phdl, cluster_dict, config_dict, request):
    '''Run the ANC item "oblex_ds_ntd".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        phdl,
        cluster_dict,
        config_dict,
        ["oblex_ds_ntd"],
        "test_oblex_ds_ntd",
        request=request,
    )


def test_oblex_metronome(phdl, cluster_dict, config_dict, request):
    '''Run the ANC item "oblex_metronome".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        phdl,
        cluster_dict,
        config_dict,
        ["oblex_metronome"],
        "test_oblex_metronome",
        request=request,
    )


def test_oblex_opt(phdl, cluster_dict, config_dict, request):
    '''Run the ANC item "oblex_opt".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        phdl,
        cluster_dict,
        config_dict,
        ["oblex_opt"],
        "test_oblex_opt",
        request=request,
    )


def test_oblex_remix2(phdl, cluster_dict, config_dict, request):
    '''Run the ANC item "oblex_remix2".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        phdl,
        cluster_dict,
        config_dict,
        ["oblex_remix2"],
        "test_oblex_remix2",
        request=request,
    )


def test_oblex_s16(phdl, cluster_dict, config_dict, request):
    '''Run the ANC item "oblex_s16".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        phdl,
        cluster_dict,
        config_dict,
        ["oblex_s16"],
        "test_oblex_s16",
        request=request,
    )


def test_oblex_s16_ds(phdl, cluster_dict, config_dict, request):
    '''Run the ANC item "oblex_s16_ds".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        phdl,
        cluster_dict,
        config_dict,
        ["oblex_s16_ds"],
        "test_oblex_s16_ds",
        request=request,
    )


def test_oblex_trad(phdl, cluster_dict, config_dict, request):
    '''Run the ANC item "oblex_trad".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        phdl,
        cluster_dict,
        config_dict,
        ["oblex_trad"],
        "test_oblex_trad",
        request=request,
    )


def test_pcie_gpu_rx_margin(phdl, cluster_dict, config_dict, request):
    '''Run the ANC item "pcie_gpu_rx_margin".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        phdl,
        cluster_dict,
        config_dict,
        ["pcie_gpu_rx_margin"],
        "test_pcie_gpu_rx_margin",
        request=request,
    )


def test_pcie_link_status(phdl, cluster_dict, config_dict, request):
    '''Run the ANC item "pcie_link_status".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        phdl,
        cluster_dict,
        config_dict,
        ["pcie_link_status"],
        "test_pcie_link_status",
        request=request,
    )


def test_pcie_nic_rx_margin(phdl, cluster_dict, config_dict, request):
    '''Run the ANC item "pcie_nic_rx_margin".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        phdl,
        cluster_dict,
        config_dict,
        ["pcie_nic_rx_margin"],
        "test_pcie_nic_rx_margin",
        request=request,
    )


def test_sdma_bidi_peak(phdl, cluster_dict, config_dict, request):
    '''Run the ANC item "sdma_bidi_peak".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        phdl,
        cluster_dict,
        config_dict,
        ["sdma_bidi_peak"],
        "test_sdma_bidi_peak",
        request=request,
    )


def test_sprites(phdl, cluster_dict, config_dict, request):
    '''Run the ANC item "sprites".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        phdl,
        cluster_dict,
        config_dict,
        ["sprites"],
        "test_sprites",
        request=request,
    )


def test_ualink_gpu_rx_margin(phdl, cluster_dict, config_dict, request):
    '''Run the ANC item "ualink_gpu_rx_margin".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        phdl,
        cluster_dict,
        config_dict,
        ["ualink_gpu_rx_margin"],
        "test_ualink_gpu_rx_margin",
        request=request,
    )


def test_ualink_nic_rx_margin(phdl, cluster_dict, config_dict, request):
    '''Run the ANC item "ualink_nic_rx_margin".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        phdl,
        cluster_dict,
        config_dict,
        ["ualink_nic_rx_margin"],
        "test_ualink_nic_rx_margin",
        request=request,
    )


def test_ualink_status(phdl, cluster_dict, config_dict, request):
    '''Run the ANC item "ualink_status".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        phdl,
        cluster_dict,
        config_dict,
        ["ualink_status"],
        "test_ualink_status",
        request=request,
    )


def test_umcinfo(phdl, cluster_dict, config_dict, request):
    '''Run the ANC item "umcinfo".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        phdl,
        cluster_dict,
        config_dict,
        ["umcinfo"],
        "test_umcinfo",
        request=request,
    )


def test_xgmi_cpu_rx_margin(phdl, cluster_dict, config_dict, request):
    '''Run the ANC item "xgmi_cpu_rx_margin".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        phdl,
        cluster_dict,
        config_dict,
        ["xgmi_cpu_rx_margin"],
        "test_xgmi_cpu_rx_margin",
        request=request,
    )


def test_xgmi_gpu_rx_margin(phdl, cluster_dict, config_dict, request):
    '''Run the ANC item "xgmi_gpu_rx_margin".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        phdl,
        cluster_dict,
        config_dict,
        ["xgmi_gpu_rx_margin"],
        "test_xgmi_gpu_rx_margin",
        request=request,
    )


def test_xgmi_link_status(phdl, cluster_dict, config_dict, request):
    '''Run the ANC item "xgmi_link_status".'''
    anc_lib.ensure_anc_ready(phdl, cluster_dict, config_dict)
    anc_lib.run_anc_items(
        phdl,
        cluster_dict,
        config_dict,
        ["xgmi_link_status"],
        "test_xgmi_link_status",
        request=request,
    )
